language: rust
env: FEATURES=""
matrix:
  include:
    - rust: 1.35.0
    - rust: stable
    - rust: beta
    - rust: nightly
script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
