language: rust
env: FEATURES=""
matrix:
  include:
    - rust: 1.17.0
    - rust: stable
    - rust: beta
    - rust: nightly
      env:
        - FEATURES=""
        - FEATURES="nightly"
script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
